export const projectObjs = [
  {
    title: "Outsource Accounting",
    description:
      "Using HTML5, CSS and JavaScript, I made an accounting website for Outsource Accounting",
    image: "/images/accounting-site.PNG",
    tags: ["HTML5", "CSS", "JavaScript"],
    source: "https://boring-torvalds-a4eea2.netlify.app/",
    visit: "https://github.com/kalemmentore868/accounting-site-for-momz",
    id: 0,
    position: [0, 0, 0],
  },
  {
    title: "Gaming Website",
    description:
      "A Landing page for a replica WIX Gaming Website, made with HTML5, CSS and JavaScript",
    image: "/images/gaming-site.PNG",
    tags: ["HTML5", "CSS", "JavaScript"],
    source: "https://hardcore-noyce-473a2a.netlify.app/",
    visit: "https://github.com/kalemmentore868/Wix-clone-project",
    id: 1,
    position: [0.18, 13, 20],
  },
  {
    title: "Calculator App",
    description:
      "A calculator app I made with HTML5, CSS and JavaScript. It also has a button which can be clicked to switch the theme",
    image: "/images/calculator-app.PNG",
    tags: ["HTML5", "CSS", "JavaScript"],
    source: "https://stupefied-hamilton-ec2f7d.netlify.app/",
    visit: "https://github.com/kalemmentore868/Calculator-app",
    id: 2,
    position: [-0.3, 20, 20],
  },
  {
    title: "Tic Tac Toe app",
    description:
      "This is a simple online game of tic tac toe made with HTML5, CSS and JavaScript",
    image: "/images/tic-tac-toe.PNG",
    tags: ["HTML5", "CSS", "JavaScript"],
    source: "https://distracted-swanson-1f879e.netlify.app/",
    visit: "https://github.com/kalemmentore868/Tic-Tac-Toe",
    id: 3,
    position: [0.2, 30, 5],
  },
  {
    title: "Easy Bank Landing Page",
    description:
      "An elegant landing page for easy bank made with HTML5, CSS and JavaScript",
    image: "/images/easy-bank.PNG",
    tags: ["HTML5", "CSS", "JavaScript"],
    source: "https://objective-heisenberg-e6ee1b.netlify.app/",
    visit: "https://github.com/kalemmentore868/Easy-Bank-Landing-Page",
    id: 4,
    position: [0.18, 10, -10],
  },
  {
    title: "Home Room Landing Page",
    description:
      "An elegant landing page for a home decor store made with HTML5, CSS and JavaScript",
    image: "/images/home-room-site.PNG",
    tags: ["HTML5", "CSS", "JavaScript"],
    source: "https://objective-snyder-e34ef0.netlify.app/",
    visit: "https://github.com/kalemmentore868/Home-Room-Landing-Page",
    id: 5,
    position: [-0.17, -6, 0],
  },
  {
    title: "Alien Invasion Math Game",
    description:
      "An HTML5 cross platform game where users destroy spaceships by answering math questions",
    image: "/images/alien-space-invasion.png",
    tags: ["HTML5", "CSS", "JavaScript"],
    source: "https://ubiquitous-semolina-e1b35c.netlify.app/",
    visit: "https://github.com/kalemmentore868/Alien-Space-Invasion",
    id: 6,
    position: [-0.26, 6, 6],
  },
  {
    title: "Demo Digi",
    description: "A replica of one of Digicel's older websites made with React",
    image: "/images/demo-digi.png",
    tags: ["React", "Javascript"],
    source: "https://magnificent-fairy-56d517.netlify.app/",
    visit: "https://github.com/kalemmentore868/Demo-digi",
    id: 7,
    position: [0.26, -6, 4],
  },
  {
    title: "BlockSquare",
    description:
      "An HTML5 cross platform game where users tap on squares to occupy space. The player who occupies the most squares wins ",
    image: "/images/blocksquare.png",
    tags: ["HTML5", "CSS", "Typescript"],
    source: "https://bloqsquare.netlify.app/",
    visit: "https://github.com/kalemmentore868/blocksquare",
    id: 7,
    position: [0, 10, 4],
  },
];
